### ISSUE TITLE
Delete comments

### ISSUE THREAD

**Issue by saykl** [fujig/VK_Delete_Comments#2]
Traceback (most recent call last):
  File "vk_delete_stuff.py", line 29, in get_comments_urls
    file_with_comments = open(open_and_find, 'r', encoding="ISO-8859-1")
FileNotFoundError: [Errno 2] No such file or directory: '/home/andrey/Archive/comments/comments6.html\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vk_delete_stuff.py", line 151, in <module>
    delete_comments(get_comments_urls(get_comments_paths()))
  File "vk_delete_stuff.py", line 44, in get_comments_urls
    file_with_comments.close()
UnboundLocalError: local variable 'file_with_comments' referenced before assignment

**Comment by hntirgeam** [comment]
master branch was merged without testing (i've no longer have an account in vk)...
 
You should try `git checkout 33a37bde81aa5e1ba3e669d69fbcb86a329436fc`  - this version I was using.
